### ISSUE TITLE
OOM when offline evaluating Faster-RCNN

### ISSUE THREAD

**Issue by BichenWuUCB** [ppwwyyxx/tensorpack#467]
Hi Yuxin,

I was able to evaluate Faster R-CNN model during training, but when I tried to evaluate the Faster-RCNN model offline, I got OOM exactly after 27 steps on K80 GPUs and 34 steps on Titan X GPUs.

Seems to be that memory consumption grows with evaluation steps. Any suggestions how to fix this?

**Comment by ppwwyyxx** [comment]
I can't reproduce this problem either.  😢 
Evaluating the model shouldn't use much memory, and since you can eval it during training I have no idea why this happens. 
If you're sure no one else is using the GPU at the same time, maybe you can try a different version of tensorflow/cudnn.

**Comment by BichenWuUCB** [comment]
Seems that it has something to do with auto tuning. I **commented** this line 

`os.environ['TF_CUDNN_USE_AUTOTUNE'] = '0'`

to enable tensorflow auto tuning and the issue is gone. Otherwise, the GPU memory keeps growing with number of evaluation steps until OOM. 

My current tensorflow version is 1.4.0 and cudnn version is 6.0.21

**Comment by ppwwyyxx** [comment]
I'm using 1.4.0rc0 and 6.0.21 as well. Any chance your issue is related to https://github.com/pytorch/pytorch/issues/1272  (nvidia driver issue)?

**Comment by ppwwyyxx** [comment]
It's probably an issue in lower level. Maybe specific to driver or GPU and their interaction with softwares like cudnn or tensorflow. I know some version of driver can cause CPU memory leak with cudnn.

Another related environment variable is `TF_CUDNN_WORKSPACE_LIMIT_IN_MB` which is default to 4G.  Although ideally it shouldn't be a problem.
Also the related code for "no-autotune" (i.e. default algorithm) is https://github.com/tensorflow/tensorflow/blob/6a8322f6dc007573e97a452e056b76f2be4794a7/tensorflow/stream_executor/cuda/cuda_dnn.cc#L2200-L2262 assuming you don't have XLA or JIT enabled, which indeed has something to do with memory, and you might find some clues from the error log if you wish. But unfortunately I cannot reproduce it, so I can't help much.

**Comment by BichenWuUCB** [comment]
Thanks Yuxin, this is very helpful. I'll look into it and let you know.

**Comment by lbin** [comment]
I got OOM exactly after 127 epoch on Titan xp GPUs.

**Comment by ppwwyyxx** [comment]
@lbin You mean in training?
And 127 epochs not steps? This sounds like a different problem.

**Comment by lbin** [comment]
Oh yes, it's my mistake. It is in traing.

<img width="1440" alt="screen shot 2017-11-06 at 10 02 02 am" src="https://user-images.githubusercontent.com/3326649/32422185-b8ce4b84-c2d9-11e7-8f84-bcfc5fe8c586.png">

**Comment by ppwwyyxx** [comment]
It's been a while now and I'm not sure if the problem still exists. I've never seen OOM but I don't have TitanX or TitanXp or K80 either. The training runs fine on M40 (also 12G memory) and P100. Others have run it successfully on V100 as well. 

With more results been published recently the code is more stable now, although I still have no clues why you guys saw OOM. I did find that using PrefetchDataZMQ here increase about 100MB GPU memory use but this is probably irrelevant.

**Comment by tranorrepository** [comment]
I got OOM error too. More information is below: 
fname, boxes, klass, is_crowd = img['file_name'], img['boxes'], img['class'], img['is_crowd']
KeyError: 'file_name'

P.S, python 3.4, tf 1.4

**Comment by ppwwyyxx** [comment]
@tranorrepository I don't understand what your issue is. Could you open an issue following the [issue template](https://github.com/ppwwyyxx/tensorpack/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by ppwwyyxx** [comment]
As a closing remark, even if this issue still exists, it's probably a very platform-specific problem because many people have already successfully used this piece of code. My last suggestions to anyone who may encounter OOM in the future: 

Make sure no other processes (e.g. Xorg) are running on GPUs.
For training, try smaller batch sizes (`FASTRCNN_BATCH_PER_IM`).
For evaluation, try smaller `TEST_POST_NMS_TOPK`.
